# Generated by Django 3.2.9 on 2022-01-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_reviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='review',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
